# Generated by Django 4.1.1 on 2022-10-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=30)),
                ('ModelName', models.CharField(max_length=30)),
                ('CarNumber', models.CharField(max_length=30)),
                ('Features', models.TextField()),
                ('IsCarBooked', models.CharField(max_length=3)),
                ('CarImage', models.ImageField(default='navimg.jpeg', upload_to='profile_pics')),
            ],
        ),
    ]
