# Generated by Django 4.1.1 on 2022-11-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cars", "0005_rename_iscarbooked_cars_isavailable"),
    ]

    operations = [
        migrations.AddField(
            model_name="otherdetails",
            name="NumberOfDays",
            field=models.IntegerField(default=1),
        ),
    ]
